name: Create NPM token
description: Creates an NPM token for a private registry

inputs:
  username:
    description: Registry username
    required: true
  password:
    description: Registry password
    required: true
  registry-url:
    description: NPM registry URL
    required: true

outputs:
  npm-token:
    description: NPM token
    value: ${{ steps.generate-token.outputs.token }}

runs:
  using: composite
  steps:
    - id: generate-token
      name: Generate NPM token
      shell: bash
      run: |
        NODE_AUTH_TOKEN=$(curl -s \
          -H "Accept: application/json" \
          -H "Content-Type:application/json" \
          -X PUT --data "{\"name\": \"${{ inputs.username }}\", \"password\": \"${{ inputs.password }}\"}" \
          ${{ inputs.registry-url }}/-/user/org.couchdb.user:${{ inputs.username }} 2>&1 | jq -r '.token')

        echo "::add-mask::$NODE_AUTH_TOKEN"
        echo "token=$NODE_AUTH_TOKEN" >> $GITHUB_OUTPUT
